spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080