spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: taskero300@gmail.com
    password: tkjf xuan jcrh jrbs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

logging:
  file:
    name: logs/app.log
  level:
    root: OFF                 # Spring + third-party libs: WARN and ERROR only
    org.example.config.RequestLogFilter: INFO
    org.example.config.ServiceExceptionLoggingAspect: INFO